CREATE TABLE users
(

    id BIGINT primary key generated by default as identity,
    user_name varchar(50) unique not null,
    password varchar(50) unique not null,
    address varchar(1000) not null,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE

);



