CREATE TABLE order_items
(

    id BIGINT primary key generated by default as identity,
    order_id BIGINT not null re,
    item_id BIGINT not null,
    item_name varchar(255) not null,
    status varchar(255) not null,
    quantity bigint not null,
    comment varchar(500),
    final_cost DOUBLE PRECISION not null,
    created_at  TIMESTAMP WITHOUT TIME ZONE,
    updated_at  TIMESTAMP WITHOUT TIME ZONE,
    FOREIGN KEY (order_id)    -- Define the foreign key
            REFERENCES orders (id)
            ON DELETE CASCADE          -- Optional: Action on delete
            ON UPDATE CASCADE

);

